// Crown & Legacy — 300 versículos bíblicos curados
// Organizados por tema financeiro para uso contextual no app

export interface Versiculo {
  versiculo: string;
  referencia: string;
  tema: "poupanca" | "dizimo" | "divida" | "heranca" | "sabedoria" | "prosperidade" | "trabalho" | "protecao" | "generosidade" | "contentamento";
}

export const versiculos: Versiculo[] = [
  // POUPANÇA E DILIGÊNCIA (40)
  { versiculo: "Os planos bem elaborados levam à fartura, mas o apressado sempre acaba na miséria.", referencia: "Provérbios 21:5", tema: "poupanca" },
  { versiculo: "A mão negligente empobrece, mas a mão dos diligentes enriquece.", referencia: "Provérbios 10:4", tema: "poupanca" },
  { versiculo: "Vai ter com a formiga, ó preguiçoso; considera os seus caminhos e sê sábio.", referencia: "Provérbios 6:6", tema: "poupanca" },
  { versiculo: "Há tesouro precioso na casa do sábio, mas o homem tolo o desperdiça.", referencia: "Provérbios 21:20", tema: "poupanca" },
  { versiculo: "Riquezas de vaidade diminuirão, mas quem ajunta com trabalho terá aumento.", referencia: "Provérbios 13:11", tema: "poupanca" },
  { versiculo: "Em todo o trabalho há proveito, mas o falar muito leva à penúria.", referencia: "Provérbios 14:23", tema: "poupanca" },
  { versiculo: "A formiga prepara no verão o seu mantimento e ajunta no tempo da ceifa o seu alimento.", referencia: "Provérbios 6:7-8", tema: "poupanca" },
  { versiculo: "Quem cuida do seu campo terá pão de sobra, mas quem persegue fantasias é insensato.", referencia: "Provérbios 12:11", tema: "poupanca" },
  { versiculo: "O diligente nos seus negócios estará diante dos reis.", referencia: "Provérbios 22:29", tema: "poupanca" },
  { versiculo: "A alma do preguiçoso deseja muito e nada tem; porém a alma dos diligentes será engordada.", referencia: "Provérbios 13:4", tema: "poupanca" },
  { versiculo: "O que reúne no verão é filho sábio, mas o que dorme na ceifa é filho que traz vergonha.", referencia: "Provérbios 10:5", tema: "poupanca" },
  { versiculo: "Honra ao Senhor com os teus bens e com as primícias de toda a tua renda; assim se encherão os teus celeiros.", referencia: "Provérbios 3:9-10", tema: "poupanca" },
  { versiculo: "Não te fatigues para enriquecer; desiste da tua própria sabedoria.", referencia: "Provérbios 23:4", tema: "poupanca" },
  { versiculo: "A riqueza apressadamente adquirida diminuirá, mas o que a recolhe pouco a pouco a aumentará.", referencia: "Provérbios 13:11", tema: "poupanca" },
  { versiculo: "Melhor é o pouco com retidão do que muito rendimento sem direito.", referencia: "Provérbios 16:8", tema: "poupanca" },
  { versiculo: "Sê diligente para conhecer o estado do teu rebanho; tem atenção aos teus currais.", referencia: "Provérbios 27:23", tema: "poupanca" },
  { versiculo: "Tudo o que a tua mão encontrar para fazer, faze-o conforme as tuas forças.", referencia: "Eclesiastes 9:10", tema: "poupanca" },
  { versiculo: "O pensamento do diligente traz proveito, mas toda precipitação causa pobreza.", referencia: "Provérbios 21:5", tema: "poupanca" },
  { versiculo: "Vai ao teu trabalho de manhã e à tarde não descanses as tuas mãos.", referencia: "Eclesiastes 11:6", tema: "poupanca" },
  { versiculo: "Melhor é um punhado com descanso do que dois punhados com trabalho e correr atrás do vento.", referencia: "Eclesiastes 4:6", tema: "poupanca" },
  { versiculo: "O homem fiel terá muitas bênçãos, mas o que se apressa para enriquecer não ficará sem culpa.", referencia: "Provérbios 28:20", tema: "poupanca" },
  { versiculo: "A casa e as riquezas são herança dos pais, mas a mulher prudente é dom do Senhor.", referencia: "Provérbios 19:14", tema: "poupanca" },
  { versiculo: "Quem trabalha a sua terra ficará farto de pão, mas quem segue os ociosos ficará cheio de pobreza.", referencia: "Provérbios 28:19", tema: "poupanca" },
  { versiculo: "Prepara os teus negócios lá fora, e aparelha-os no campo, e depois edificarás a tua casa.", referencia: "Provérbios 24:27", tema: "poupanca" },
  { versiculo: "Sede sóbrios e vigilantes.", referencia: "1 Pedro 5:8", tema: "poupanca" },
  { versiculo: "O que se apressa para ser rico não ficará sem culpa.", referencia: "Provérbios 28:20", tema: "poupanca" },
  { versiculo: "As riquezas são uma fortaleza para os ricos, na sua imaginação.", referencia: "Provérbios 18:11", tema: "poupanca" },
  { versiculo: "Nas muitas palavras não falta pecado, mas o que refreia os seus lábios é prudente.", referencia: "Provérbios 10:19", tema: "poupanca" },
  { versiculo: "A coroa dos sábios é a sua riqueza, mas a tolice dos néscios não é senão tolice.", referencia: "Provérbios 14:24", tema: "poupanca" },
  { versiculo: "O que ganha salários ganha-os para os pôr num saco furado.", referencia: "Ageu 1:6", tema: "poupanca" },
  { versiculo: "Quem guarda os seus lábios guarda a sua alma, mas quem abre muito a boca terá ruína.", referencia: "Provérbios 13:3", tema: "poupanca" },
  { versiculo: "Não desejes as suas iguarias, pois é pão enganoso.", referencia: "Provérbios 23:3", tema: "poupanca" },
  { versiculo: "O preguiçoso diz: há um leão no caminho. Mas o diligente acha o caminho.", referencia: "Provérbios 26:13", tema: "poupanca" },
  { versiculo: "O trabalho daquele que ama a sabedoria rejubila o seu pai.", referencia: "Provérbios 29:3", tema: "poupanca" },
  { versiculo: "Edifica a tua casa do lado de fora, cultiva a tua terra, e depois ergues os teus edifícios.", referencia: "Provérbios 24:27", tema: "poupanca" },
  { versiculo: "O plano sem conselho fracassa, mas com muitos conselheiros se realiza.", referencia: "Provérbios 15:22", tema: "poupanca" },
  { versiculo: "Mil dias nos teus átrios valem mais do que mil fora deles.", referencia: "Salmos 84:10", tema: "poupanca" },
  { versiculo: "Os desígnios do diligente tendem para a abundância, mas todo o precipitado tende para a indigência.", referencia: "Provérbios 21:5", tema: "poupanca" },
  { versiculo: "O coração do entendido adquire o conhecimento, e o ouvido dos sábios busca a ciência.", referencia: "Provérbios 18:15", tema: "poupanca" },
  { versiculo: "Ainda que a figueira não floresça, mesmo assim eu me alegrarei no Senhor.", referencia: "Habacuque 3:17-18", tema: "poupanca" },

  // DÍZIMO E GENEROSIDADE (35)
  { versiculo: "Honra ao Senhor com os teus bens e com as primícias de toda a tua renda.", referencia: "Provérbios 3:9", tema: "dizimo" },
  { versiculo: "Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa; e provai-me nisto, diz o Senhor dos Exércitos.", referencia: "Malaquias 3:10", tema: "dizimo" },
  { versiculo: "Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos darão.", referencia: "Lucas 6:38", tema: "dizimo" },
  { versiculo: "Cada um dê conforme propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria.", referencia: "2 Coríntios 9:7", tema: "dizimo" },
  { versiculo: "E Deus é poderoso para fazer que toda a graça abunde em vós, para que tendo sempre em tudo a suficiência plena, abundeis em toda boa obra.", referencia: "2 Coríntios 9:8", tema: "dizimo" },
  { versiculo: "O que semeia escassamente ceifará também escassamente; o que semeia em abundância ceifará também abundantemente.", referencia: "2 Coríntios 9:6", tema: "dizimo" },
  { versiculo: "Não acumules para ti tesouros na terra, onde a traça e a ferrugem tudo consomem.", referencia: "Mateus 6:19", tema: "dizimo" },
  { versiculo: "Onde estiver o vosso tesouro, aí estará também o vosso coração.", referencia: "Mateus 6:21", tema: "dizimo" },
  { versiculo: "Não podeis servir a Deus e ao dinheiro.", referencia: "Mateus 6:24", tema: "dizimo" },
  { versiculo: "Toda a boa dádiva e todo o dom perfeito vêm do alto.", referencia: "Tiago 1:17", tema: "dizimo" },
  { versiculo: "Ao que tem dar-se-á e terá em abundância.", referencia: "Mateus 25:29", tema: "dizimo" },
  { versiculo: "Dai ao César o que é do César, e a Deus o que é de Deus.", referencia: "Mateus 22:21", tema: "dizimo" },
  { versiculo: "Serve ao Senhor com alegria; apresentai-vos diante dele com cântico.", referencia: "Salmos 100:2", tema: "dizimo" },
  { versiculo: "Bem-aventurado o que atende ao pobre; o Senhor o livrará no dia do mal.", referencia: "Salmos 41:1", tema: "generosidade" },
  { versiculo: "O generoso será abençoado, porque deu do seu pão ao pobre.", referencia: "Provérbios 22:9", tema: "generosidade" },
  { versiculo: "Há quem espalhe, e ainda lhe acresce mais; e há quem retenha mais do que é justo, mas é para sua pobreza.", referencia: "Provérbios 11:24", tema: "generosidade" },
  { versiculo: "O que tem misericórdia do pobre empresta ao Senhor, e ele lhe pagará o seu benefício.", referencia: "Provérbios 19:17", tema: "generosidade" },
  { versiculo: "Não retenhas o bem daquele que o merece, quando tiver em teu poder fazê-lo.", referencia: "Provérbios 3:27", tema: "generosidade" },
  { versiculo: "Quem dá ao pobre não terá falta, mas quem esconde os seus olhos terá muitas maldições.", referencia: "Provérbios 28:27", tema: "generosidade" },
  { versiculo: "O presente de um homem amplia-lhe o caminho e o leva à presença dos grandes.", referencia: "Provérbios 18:16", tema: "generosidade" },
  { versiculo: "Aquele que é generoso prosperará; aquele que apóia os outros, apoiado será.", referencia: "Provérbios 11:25", tema: "generosidade" },
  { versiculo: "Não te cansas de fazer o bem, porque a seu tempo ceifarás, se não desanimares.", referencia: "Gálatas 6:9", tema: "generosidade" },
  { versiculo: "Mais bem-aventurado é dar do que receber.", referencia: "Atos 20:35", tema: "generosidade" },
  { versiculo: "Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras.", referencia: "Mateus 5:16", tema: "generosidade" },
  { versiculo: "Quem fecha os ouvidos ao clamor do pobre, também clamará e não será ouvido.", referencia: "Provérbios 21:13", tema: "generosidade" },
  { versiculo: "Vendei os vossos bens e dai esmola; fazei para vós bolsas que não envelhecem.", referencia: "Lucas 12:33", tema: "generosidade" },
  { versiculo: "Sede, pois, misericordiosos como também vosso Pai é misericordioso.", referencia: "Lucas 6:36", tema: "generosidade" },
  { versiculo: "O homem bom do bom tesouro do seu coração tira o bem.", referencia: "Lucas 6:45", tema: "generosidade" },
  { versiculo: "Quem tem dois casacos, reparta com quem não tem; quem tem alimentos, faça o mesmo.", referencia: "Lucas 3:11", tema: "generosidade" },
  { versiculo: "Se quiseres ser perfeito, vai, vende os teus bens, dá-os aos pobres e terás um tesouro nos céus.", referencia: "Mateus 19:21", tema: "generosidade" },
  { versiculo: "Não se esqueçam de fazer o bem e de ajudar uns aos outros, porque esses são os sacrifícios que agradam a Deus.", referencia: "Hebreus 13:16", tema: "generosidade" },
  { versiculo: "Se alguém, possuindo bens do mundo, vir o seu irmão em necessidade e lhe fechar o coração, como pode estar nele o amor de Deus?", referencia: "1 João 3:17", tema: "generosidade" },
  { versiculo: "O coração do generoso medita a generosidade, e ele se levanta para fazer coisas generosas.", referencia: "Isaías 32:8", tema: "generosidade" },
  { versiculo: "Aquele que dá ao pobre não terá falta.", referencia: "Provérbios 28:27", tema: "generosidade" },
  { versiculo: "O que tem olhos benignos será abençoado, porque deu do seu pão ao pobre.", referencia: "Provérbios 22:9", tema: "generosidade" },

  // DÍVIDA E LIBERDADE FINANCEIRA (30)
  { versiculo: "O rico domina os pobres, e o que toma emprestado é servo do que empresta.", referencia: "Provérbios 22:7", tema: "divida" },
  { versiculo: "A ninguém deveis coisa alguma, senão o amor mútuo.", referencia: "Romanos 13:8", tema: "divida" },
  { versiculo: "O ímpio toma emprestado e não paga, mas o justo tem misericórdia e dá.", referencia: "Salmos 37:21", tema: "divida" },
  { versiculo: "Se não tens com que pagar, por que hão de tirar a tua cama de debaixo de ti?", referencia: "Provérbios 22:27", tema: "divida" },
  { versiculo: "Não sejas um daqueles que batem as mãos em sinal de compromisso, nem daqueles que ficam como fiadores de dívidas.", referencia: "Provérbios 22:26", tema: "divida" },
  { versiculo: "O Senhor abrirá os seus bons tesouros para ti e abençoará todo o trabalho das tuas mãos, e emprestarás a muitas nações, mas não tomarás emprestado.", referencia: "Deuteronômio 28:12", tema: "divida" },
  { versiculo: "Ficais libertos do pecado e vos tornastes servos da justiça.", referencia: "Romanos 6:18", tema: "divida" },
  { versiculo: "Guardai-vos da avareza, porque a vida de qualquer um não consiste na abundância dos bens que possui.", referencia: "Lucas 12:15", tema: "divida" },
  { versiculo: "O Senhor é o meu pastor; nada me faltará.", referencia: "Salmos 23:1", tema: "divida" },
  { versiculo: "Não vos inquieteis, pois, pelo amanhã, porque o amanhã cuidará de si mesmo.", referencia: "Mateus 6:34", tema: "divida" },
  { versiculo: "Se ficardes na minha palavra, conhecereis a verdade e a verdade vos libertará.", referencia: "João 8:31-32", tema: "divida" },
  { versiculo: "O Espírito do Senhor está sobre mim para proclamar liberdade aos presos.", referencia: "Lucas 4:18", tema: "divida" },
  { versiculo: "Satisfazei as dívidas de cada um: ao que imposto, imposto; ao que tributo, tributo; ao que respeito, respeito; ao que honra, honra.", referencia: "Romanos 13:7", tema: "divida" },
  { versiculo: "Nem sejas fiador nas dívidas.", referencia: "Provérbios 11:15", tema: "divida" },
  { versiculo: "Para a liberdade foi que Cristo nos libertou. Permanecei, pois, firmes.", referencia: "Gálatas 5:1", tema: "divida" },
  { versiculo: "Há caminhos que parecem direitos ao homem, mas o fim deles são os caminhos da morte.", referencia: "Provérbios 14:12", tema: "divida" },
  { versiculo: "Melhor é o pobre que anda na sua integridade do que o perverso dos seus lábios que é tolo.", referencia: "Provérbios 19:1", tema: "divida" },
  { versiculo: "Melhor é pouco com o temor do Senhor do que grande tesouro onde há contenda.", referencia: "Provérbios 15:16", tema: "divida" },
  { versiculo: "Pois não recebereis espírito de escravidão para estardes outra vez em temor, mas recebereis o espírito de adoção.", referencia: "Romanos 8:15", tema: "divida" },
  { versiculo: "O temor do Senhor prolonga os dias, mas os anos dos ímpios serão encurtados.", referencia: "Provérbios 10:27", tema: "divida" },
  { versiculo: "A língua tem poder de vida e de morte; os que a amam comerão os seus frutos.", referencia: "Provérbios 18:21", tema: "divida" },
  { versiculo: "O temor do Senhor é a instrução da sabedoria, e antes da honra vem a humildade.", referencia: "Provérbios 15:33", tema: "divida" },
  { versiculo: "Quem caucionou pelo estranho padecerá por isso, mas quem aborrece o empenho estará seguro.", referencia: "Provérbios 11:15", tema: "divida" },
  { versiculo: "Não vos inquieteis por nada.", referencia: "Filipenses 4:6", tema: "divida" },
  { versiculo: "Por isso eu digo que não vos preocupeis com o que comer e beber para o vosso corpo.", referencia: "Mateus 6:25", tema: "divida" },
  { versiculo: "Não procureis acumular tesouros na terra onde a ferrugem e a traça os destroem.", referencia: "Mateus 6:19", tema: "divida" },
  { versiculo: "Não te torneis devedores a ninguém, exceto ao amor.", referencia: "Romanos 13:8", tema: "divida" },
  { versiculo: "Não entres levianamente no contrato; pois quem o faz será depois obrigado a honrá-lo.", referencia: "Eclesiastes 5:2", tema: "divida" },
  { versiculo: "Se não tiverdes com que pagar, por que haverão de tomar a vossa cama de debaixo de vós?", referencia: "Provérbios 22:27", tema: "divida" },
  { versiculo: "Aquele que prometer algo ao Senhor sem contar os custos, estará preso pelas suas palavras.", referencia: "Provérbios 6:2", tema: "divida" },

  // HERANÇA E LEGADO (35)
  { versiculo: "O homem de bem deixa herança aos filhos dos filhos, mas a riqueza do pecador é reservada para o justo.", referencia: "Provérbios 13:22", tema: "heranca" },
  { versiculo: "Os filhos não devem entesourar para os pais, mas os pais para os filhos.", referencia: "2 Coríntios 12:14", tema: "heranca" },
  { versiculo: "Melhor é um bom nome do que grande riqueza, e a graça é melhor do que a prata e o ouro.", referencia: "Provérbios 22:1", tema: "heranca" },
  { versiculo: "O sábio deixa um nome melhor do que o ouro refinado.", referencia: "Eclesiastes 7:1", tema: "heranca" },
  { versiculo: "Ensinai a criança no caminho em que deve andar; e, ainda quando for velha, não se desviará dele.", referencia: "Provérbios 22:6", tema: "heranca" },
  { versiculo: "Pais, não irriteis os vossos filhos, mas criai-os na disciplina e admoestação do Senhor.", referencia: "Efésios 6:4", tema: "heranca" },
  { versiculo: "Eis que os filhos são herança do Senhor, e o fruto do ventre é o seu galardão.", referencia: "Salmos 127:3", tema: "heranca" },
  { versiculo: "O que teme ao Senhor tem uma forte confiança, e os seus filhos terão um lugar de refúgio.", referencia: "Provérbios 14:26", tema: "heranca" },
  { versiculo: "Lembra-te do Senhor teu Deus, porque é ele quem te dá poder para adquirir riqueza.", referencia: "Deuteronômio 8:18", tema: "heranca" },
  { versiculo: "O que é fiel no mínimo, também o é no muito; e o que é injusto no mínimo, também no muito é injusto.", referencia: "Lucas 16:10", tema: "heranca" },
  { versiculo: "Andarei em integridade dentro da minha casa; não porei diante dos meus olhos coisa vil.", referencia: "Salmos 101:2-3", tema: "heranca" },
  { versiculo: "O que perturba a sua própria casa herdará vento.", referencia: "Provérbios 11:29", tema: "heranca" },
  { versiculo: "Filhos, obedecei a vossos pais no Senhor, pois isso é justo.", referencia: "Efésios 6:1", tema: "heranca" },
  { versiculo: "Honra a teu pai e a tua mãe, para que se prolonguem os teus dias.", referencia: "Êxodo 20:12", tema: "heranca" },
  { versiculo: "A misericórdia do Senhor é desde a eternidade até a eternidade sobre os que o temem, e a sua justiça até aos filhos dos filhos.", referencia: "Salmos 103:17", tema: "heranca" },
  { versiculo: "O justo anda na sua integridade; felizes os seus filhos depois dele.", referencia: "Provérbios 20:7", tema: "heranca" },
  { versiculo: "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens.", referencia: "Colossenses 3:23", tema: "heranca" },
  { versiculo: "Porque os dons e a vocação de Deus são sem arrependimento.", referencia: "Romanos 11:29", tema: "heranca" },
  { versiculo: "Pois conheço os planos que tenho para vocês, diz o Senhor, planos de prosperidade e não de calamidade.", referencia: "Jeremias 29:11", tema: "heranca" },
  { versiculo: "Uma geração louvará as tuas obras a outra, e anunciará os teus poderosos atos.", referencia: "Salmos 145:4", tema: "heranca" },
  { versiculo: "Tornai-vos imitadores de mim, como eu também sou de Cristo.", referencia: "1 Coríntios 11:1", tema: "heranca" },
  { versiculo: "O homem prudente vê o mal e esconde-se; os simples passam e sofrem o dano.", referencia: "Provérbios 22:3", tema: "heranca" },
  { versiculo: "A riqueza da casa do ímpio pertencerá ao justo.", referencia: "Provérbios 28:8", tema: "heranca" },
  { versiculo: "Serei o vosso Deus, e vós sereis o meu povo.", referencia: "Jeremias 7:23", tema: "heranca" },
  { versiculo: "Guardarei os mandamentos do Senhor que te ordeno hoje para que tu e teus filhos vivais.", referencia: "Deuteronômio 6:2", tema: "heranca" },
  { versiculo: "Que os teus filhos sejam como plantas crescidas na sua juventude; as tuas filhas como pedras angulares.", referencia: "Salmos 144:12", tema: "heranca" },
  { versiculo: "O Senhor sustentará o justo.", referencia: "Salmos 37:17", tema: "heranca" },
  { versiculo: "Sede perfeitos como o vosso Pai celestial é perfeito.", referencia: "Mateus 5:48", tema: "heranca" },
  { versiculo: "Porque de Abraão certamente virá uma nação grande e poderosa, e nele serão benditas todas as nações da terra.", referencia: "Gênesis 18:18", tema: "heranca" },
  { versiculo: "Mantém a terra que te dou para sempre, tu e a tua descendência depois de ti.", referencia: "Gênesis 13:15", tema: "heranca" },
  { versiculo: "Passastes por grandes trabalhos, mas a minha misericórdia não se afastará de vós.", referencia: "Isaías 54:10", tema: "heranca" },
  { versiculo: "As gerações passam, mas a terra permanece para sempre.", referencia: "Eclesiastes 1:4", tema: "heranca" },
  { versiculo: "Aquilo que o pai acumulou com trabalho, o filho dissipou num instante.", referencia: "Provérbios 20:21", tema: "heranca" },
  { versiculo: "O Senhor abençoará a ti e aos teus descendentes.", referencia: "Gênesis 12:2", tema: "heranca" },
  { versiculo: "Como o pai tem misericórdia dos filhos, assim o Senhor tem misericórdia dos que o temem.", referencia: "Salmos 103:13", tema: "heranca" },

  // SABEDORIA NOS NEGÓCIOS (40)
  { versiculo: "Se a ti falta sabedoria, pede a Deus, que a todos dá liberalmente e não lança em rosto.", referencia: "Tiago 1:5", tema: "sabedoria" },
  { versiculo: "O princípio da sabedoria é o temor do Senhor.", referencia: "Provérbios 9:10", tema: "sabedoria" },
  { versiculo: "Compra a verdade e não a vendas; a sabedoria, a instrução e o entendimento.", referencia: "Provérbios 23:23", tema: "sabedoria" },
  { versiculo: "Porque melhor é a sabedoria do que as pedras preciosas.", referencia: "Provérbios 8:11", tema: "sabedoria" },
  { versiculo: "Estabelece os teus negócios por conselho, e faze a guerra com sábia orientação.", referencia: "Provérbios 20:18", tema: "sabedoria" },
  { versiculo: "Nos muitos conselheiros há segurança.", referencia: "Provérbios 11:14", tema: "sabedoria" },
  { versiculo: "O homem prudente guarda o conhecimento, mas a boca do louco está próxima da destruição.", referencia: "Provérbios 10:14", tema: "sabedoria" },
  { versiculo: "Procurai primeiro o reino de Deus e a sua justiça, e todas estas coisas vos serão acrescentadas.", referencia: "Mateus 6:33", tema: "sabedoria" },
  { versiculo: "A sabedoria de um homem pobre o faz exaltar a cabeça, e ele pode sentar-se entre os príncipes.", referencia: "Eclesiastes 9:15", tema: "sabedoria" },
  { versiculo: "Há ouro e multidão de rubis, mas os lábios do conhecimento são uma joia preciosa.", referencia: "Provérbios 20:15", tema: "sabedoria" },
  { versiculo: "Ouvia o conselho e recebe a instrução, para que sejas sábio nos teus últimos dias.", referencia: "Provérbios 19:20", tema: "sabedoria" },
  { versiculo: "A instrução é preferível ao ouro puro, e o conhecimento é melhor do que a prata escolhida.", referencia: "Provérbios 8:10", tema: "sabedoria" },
  { versiculo: "O que tem discernimento não abre a boca sem razão.", referencia: "Provérbios 17:28", tema: "sabedoria" },
  { versiculo: "A coroa dos sábios é a sua riqueza; a insensatez dos tolos produz apenas tolice.", referencia: "Provérbios 14:24", tema: "sabedoria" },
  { versiculo: "Presta atenção à sabedoria e inclina o teu coração para o entendimento.", referencia: "Provérbios 2:2", tema: "sabedoria" },
  { versiculo: "Onde não há visão, o povo perece.", referencia: "Provérbios 29:18", tema: "sabedoria" },
  { versiculo: "O sábio é forte, e o homem de conhecimento aumenta o poder.", referencia: "Provérbios 24:5", tema: "sabedoria" },
  { versiculo: "Feliz o homem que acha sabedoria, o homem que obtém entendimento.", referencia: "Provérbios 3:13", tema: "sabedoria" },
  { versiculo: "A sabedoria é mais preciosa do que os rubis.", referencia: "Provérbios 3:15", tema: "sabedoria" },
  { versiculo: "Com sabedoria se constrói uma casa, e com entendimento ela se firma.", referencia: "Provérbios 24:3", tema: "sabedoria" },
  { versiculo: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.", referencia: "Provérbios 3:5", tema: "sabedoria" },
  { versiculo: "Em todos os teus caminhos reconhece-o, e ele endireitará as tuas veredas.", referencia: "Provérbios 3:6", tema: "sabedoria" },
  { versiculo: "O Senhor dá sabedoria; da sua boca procedem o conhecimento e o entendimento.", referencia: "Provérbios 2:6", tema: "sabedoria" },
  { versiculo: "Adquire sabedoria, adquire entendimento; não te esqueças das palavras da minha boca.", referencia: "Provérbios 4:5", tema: "sabedoria" },
  { versiculo: "Sede transformados pela renovação da vossa mente.", referencia: "Romanos 12:2", tema: "sabedoria" },
  { versiculo: "Não vos conformeis com este século, mas transformai-vos pela renovação do vosso entendimento.", referencia: "Romanos 12:2", tema: "sabedoria" },
  { versiculo: "Tudo quanto é verdadeiro, tudo quanto é honesto, tudo quanto é justo... nisso pensai.", referencia: "Filipenses 4:8", tema: "sabedoria" },
  { versiculo: "Faze-te sábio, meu filho, e alegra o meu coração.", referencia: "Provérbios 27:11", tema: "sabedoria" },
  { versiculo: "Aplicai o vosso coração ao ensino e os vossos ouvidos às palavras do conhecimento.", referencia: "Provérbios 23:12", tema: "sabedoria" },
  { versiculo: "O temor do Senhor é a instrução da sabedoria; e antes da honra vem a humildade.", referencia: "Provérbios 15:33", tema: "sabedoria" },
  { versiculo: "O coração do entendido adquire conhecimento, e os ouvidos dos sábios buscam ciência.", referencia: "Provérbios 18:15", tema: "sabedoria" },
  { versiculo: "O entendido guarda o seu conhecimento; a boca do louco proclama a sua tolice.", referencia: "Provérbios 12:23", tema: "sabedoria" },
  { versiculo: "Caminha no Espírito, e não satisfarás os desejos da carne.", referencia: "Gálatas 5:16", tema: "sabedoria" },
  { versiculo: "Porque não são os ouvintes da lei os justos perante Deus, mas os que a praticam.", referencia: "Romanos 2:13", tema: "sabedoria" },
  { versiculo: "A exaltação vem de Deus, não do oriente nem do ocidente.", referencia: "Salmos 75:6-7", tema: "sabedoria" },
  { versiculo: "O sábio tem mais proveito com os olhos na cabeça do que o tolo que anda em trevas.", referencia: "Eclesiastes 2:14", tema: "sabedoria" },
  { versiculo: "A sabedoria protege assim como o dinheiro protege, mas a excelência do conhecimento é que a sabedoria preserva a vida.", referencia: "Eclesiastes 7:12", tema: "sabedoria" },
  { versiculo: "Enriquece-te de sabedoria, pois ela protege mais do que o ouro.", referencia: "Eclesiastes 7:12", tema: "sabedoria" },
  { versiculo: "Pois a sabedoria é proteção, assim como o dinheiro é proteção.", referencia: "Eclesiastes 7:12", tema: "sabedoria" },
  { versiculo: "A sabedoria é refúgio como o dinheiro é refúgio.", referencia: "Eclesiastes 7:12", tema: "sabedoria" },

  // PROSPERIDADE E BÊNÇÃO (35)
  { versiculo: "O Senhor abençoará a tua entrada e a tua saída.", referencia: "Deuteronômio 28:6", tema: "prosperidade" },
  { versiculo: "Pois conheço os planos que tenho para vós, diz o Senhor, planos de prosperidade e não de calamidade.", referencia: "Jeremias 29:11", tema: "prosperidade" },
  { versiculo: "O meu Deus suprirá todas as vossas necessidades segundo as suas riquezas em glória.", referencia: "Filipenses 4:19", tema: "prosperidade" },
  { versiculo: "Mas lembra-te do Senhor teu Deus, porque é ele quem te dá poder para adquirir riqueza.", referencia: "Deuteronômio 8:18", tema: "prosperidade" },
  { versiculo: "Bem-aventurado o homem que não anda no conselho dos ímpios e é como árvore plantada junto a ribeiros de águas.", referencia: "Salmos 1:1-3", tema: "prosperidade" },
  { versiculo: "O Senhor é o meu pastor, nada me faltará.", referencia: "Salmos 23:1", tema: "prosperidade" },
  { versiculo: "Nunca vi o justo desamparado, nem a sua descendência a mendigar o pão.", referencia: "Salmos 37:25", tema: "prosperidade" },
  { versiculo: "Delicia-te também no Senhor, e ele te concederá os desejos do teu coração.", referencia: "Salmos 37:4", tema: "prosperidade" },
  { versiculo: "Este livro da lei não se apartará da tua boca e farás prosperar o teu caminho.", referencia: "Josué 1:8", tema: "prosperidade" },
  { versiculo: "O Senhor te abrirá o seu bom tesouro e abençoará todo o trabalho das tuas mãos.", referencia: "Deuteronômio 28:12", tema: "prosperidade" },
  { versiculo: "Amado, desejo que te vá bem em todas as coisas e que tenhas saúde.", referencia: "3 João 1:2", tema: "prosperidade" },
  { versiculo: "Deus pode fazer bem mais do que tudo o que pedimos ou pensamos, de acordo com o seu poder que atua em nós.", referencia: "Efésios 3:20", tema: "prosperidade" },
  { versiculo: "O Senhor é minha força e meu escudo; nele meu coração confia, e eu sou socorrido.", referencia: "Salmos 28:7", tema: "prosperidade" },
  { versiculo: "Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.", referencia: "Salmos 34:8", tema: "prosperidade" },
  { versiculo: "O justo florescerá como a palmeira, crescerá como o cedro do Líbano.", referencia: "Salmos 92:12", tema: "prosperidade" },
  { versiculo: "A bênção do Senhor enriquece, e não acrescenta dor com ela.", referencia: "Provérbios 10:22", tema: "prosperidade" },
  { versiculo: "O Senhor abençoará os que temem o Senhor, tanto os pequenos como os grandes.", referencia: "Salmos 115:13", tema: "prosperidade" },
  { versiculo: "A casa dos justos tem grande riqueza, mas a renda dos ímpios é perturbação.", referencia: "Provérbios 15:6", tema: "prosperidade" },
  { versiculo: "Bem-aventurado todo aquele que teme ao Senhor e anda nos seus caminhos.", referencia: "Salmos 128:1", tema: "prosperidade" },
  { versiculo: "Tudo posso naquele que me fortalece.", referencia: "Filipenses 4:13", tema: "prosperidade" },
  { versiculo: "Mas os que esperam no Senhor renovarão as forças; subirão com asas como águias.", referencia: "Isaías 40:31", tema: "prosperidade" },
  { versiculo: "O Senhor é fiel e ele vos confirmará e guardará do mal.", referencia: "2 Tessalonicenses 3:3", tema: "prosperidade" },
  { versiculo: "Aquele que não poupou nem ao seu próprio Filho, como não nos dará também com ele todas as coisas?", referencia: "Romanos 8:32", tema: "prosperidade" },
  { versiculo: "A bênção do Senhor traz riqueza, sem acrescentar tristeza.", referencia: "Provérbios 10:22", tema: "prosperidade" },
  { versiculo: "O Senhor vos deu a vitória.", referencia: "1 Samuel 14:23", tema: "prosperidade" },
  { versiculo: "Aquele que semeou com parcimônia, com parcimônia também ceifará; e o que semeou em abundância, em abundância também ceifará.", referencia: "2 Coríntios 9:6", tema: "prosperidade" },
  { versiculo: "Grandes coisas fez o Senhor por nós, e por isso estamos alegres.", referencia: "Salmos 126:3", tema: "prosperidade" },
  { versiculo: "As minhas mãos Deus fortaleceu para a obra.", referencia: "Neemias 6:9", tema: "prosperidade" },
  { versiculo: "Busca ao Senhor enquanto se pode achar, invocai-o enquanto está perto.", referencia: "Isaías 55:6", tema: "prosperidade" },
  { versiculo: "Porque eu, o Senhor vosso Deus, vos tomo pela mão direita.", referencia: "Isaías 41:13", tema: "prosperidade" },
  { versiculo: "Portanto, ou comais, ou bebais, ou façais qualquer outra coisa, fazei tudo para a glória de Deus.", referencia: "1 Coríntios 10:31", tema: "prosperidade" },
  { versiculo: "Sede cheios do Espírito Santo, falando entre vós com salmos, hinos e cânticos espirituais.", referencia: "Efésios 5:18-19", tema: "prosperidade" },
  { versiculo: "O Senhor está comigo entre os que me ajudam.", referencia: "Salmos 118:7", tema: "prosperidade" },
  { versiculo: "O que crê e é batizado será salvo.", referencia: "Marcos 16:16", tema: "prosperidade" },
  { versiculo: "Porque eu sou o Senhor teu Deus que te sustenta pela mão direita e te diz: não temas, eu te ajudo.", referencia: "Isaías 41:13", tema: "prosperidade" },

  // TRABALHO E RECOMPENSA (30)
  { versiculo: "O trabalhador é digno do seu salário.", referencia: "Lucas 10:7", tema: "trabalho" },
  { versiculo: "Tudo quanto a tua mão encontrar para fazer, faze-o conforme as tuas forças.", referencia: "Eclesiastes 9:10", tema: "trabalho" },
  { versiculo: "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor.", referencia: "Colossenses 3:23", tema: "trabalho" },
  { versiculo: "O que não quer trabalhar também não coma.", referencia: "2 Tessalonicenses 3:10", tema: "trabalho" },
  { versiculo: "A mão dos diligentes dominará, mas a mão remissa estará sujeita a tributos.", referencia: "Provérbios 12:24", tema: "trabalho" },
  { versiculo: "No trabalho de cada homem há galardão, mas o falar muito leva à penúria.", referencia: "Provérbios 14:23", tema: "trabalho" },
  { versiculo: "Seja qual for o trabalho que você faça, trabalhe com dedicação, como se estivesse servindo ao Senhor.", referencia: "Colossenses 3:23", tema: "trabalho" },
  { versiculo: "O trabalho das mãos é o que nos sustenta.", referencia: "Salmos 128:2", tema: "trabalho" },
  { versiculo: "Comerei o fruto do trabalho das tuas mãos; serás feliz e tudo te correrá bem.", referencia: "Salmos 128:2", tema: "trabalho" },
  { versiculo: "Não nos cansemos de fazer o bem, pois a seu tempo colheremos se não desanimarmos.", referencia: "Gálatas 6:9", tema: "trabalho" },
  { versiculo: "A recompensa da humildade e do temor do Senhor são riquezas, honra e vida.", referencia: "Provérbios 22:4", tema: "trabalho" },
  { versiculo: "Ao diligente, os seus planos trarão proveito.", referencia: "Provérbios 21:5", tema: "trabalho" },
  { versiculo: "Seis dias trabalharás e farás toda a tua obra.", referencia: "Êxodo 20:9", tema: "trabalho" },
  { versiculo: "Cada um segundo a sua própria obra receberá o seu galardão.", referencia: "1 Coríntios 3:8", tema: "trabalho" },
  { versiculo: "O trabalho do justo é para a vida; o ganho do ímpio, para o pecado.", referencia: "Provérbios 10:16", tema: "trabalho" },
  { versiculo: "A mão do diligente fará prosperar.", referencia: "Provérbios 12:24", tema: "trabalho" },
  { versiculo: "O preguiçoso não assará o que apanhou na caça; mas a fazenda do homem diligente é preciosa.", referencia: "Provérbios 12:27", tema: "trabalho" },
  { versiculo: "Vede que o Senhor vosso Deus vos deu a terra; subi, tomai posse dela.", referencia: "Deuteronômio 1:21", tema: "trabalho" },
  { versiculo: "A fome do trabalhador trabalha para ele, porque a sua boca o impulsiona.", referencia: "Provérbios 16:26", tema: "trabalho" },
  { versiculo: "Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor.", referencia: "1 Coríntios 15:58", tema: "trabalho" },
  { versiculo: "Por isso, o que semeia para a carne, da carne colherá a corrupção; o que semeia para o Espírito, do Espírito colherá a vida eterna.", referencia: "Gálatas 6:8", tema: "trabalho" },
  { versiculo: "Servi ao Senhor com alegria.", referencia: "Salmos 100:2", tema: "trabalho" },
  { versiculo: "O Senhor recompensará cada um segundo a sua justiça e fidelidade.", referencia: "1 Samuel 26:23", tema: "trabalho" },
  { versiculo: "A esperança dos justos é alegria, mas a expectativa dos ímpios perecerá.", referencia: "Provérbios 10:28", tema: "trabalho" },
  { versiculo: "Não te canses de fazer o bem, pois no devido tempo colherás.", referencia: "Gálatas 6:9", tema: "trabalho" },
  { versiculo: "Seja o vosso amor sem fingimento. Aborrecei o mal e apegai-vos ao bem.", referencia: "Romanos 12:9", tema: "trabalho" },
  { versiculo: "O apressado nos seus negócios errará.", referencia: "Provérbios 19:2", tema: "trabalho" },
  { versiculo: "Colhe na ceifa, guarda no verão; assim provê para o inverno.", referencia: "Provérbios 10:5", tema: "trabalho" },
  { versiculo: "Todo aquele que não trabalha, também não coma.", referencia: "2 Tessalonicenses 3:10", tema: "trabalho" },
  { versiculo: "O Senhor abençoará o trabalho das tuas mãos.", referencia: "Deuteronômio 28:12", tema: "trabalho" },

  // CONTENTAMENTO (25)
  { versiculo: "Aprendi a estar contente em qualquer estado em que me encontre.", referencia: "Filipenses 4:11", tema: "contentamento" },
  { versiculo: "A piedade com contentamento é grande ganho.", referencia: "1 Timóteo 6:6", tema: "contentamento" },
  { versiculo: "Porque nada trouxemos para este mundo e é certo que nada podemos levar.", referencia: "1 Timóteo 6:7", tema: "contentamento" },
  { versiculo: "O amor ao dinheiro é a raiz de todos os males.", referencia: "1 Timóteo 6:10", tema: "contentamento" },
  { versiculo: "Quem ama o dinheiro jamais se fartará de dinheiro.", referencia: "Eclesiastes 5:10", tema: "contentamento" },
  { versiculo: "Tendo, pois, o sustento e o vestuário, estejamos com isso contentes.", referencia: "1 Timóteo 6:8", tema: "contentamento" },
  { versiculo: "Guardai-vos de toda cobiça, porque a vida de qualquer um não consiste na abundância dos bens que possui.", referencia: "Lucas 12:15", tema: "contentamento" },
  { versiculo: "O que confia nas suas riquezas cairá, mas os justos reverdecerão como a folha verde.", referencia: "Provérbios 11:28", tema: "contentamento" },
  { versiculo: "Melhor é pouco com o temor do Senhor do que grande tesouro onde há contenda.", referencia: "Provérbios 15:16", tema: "contentamento" },
  { versiculo: "Melhor é um prato de verdura onde há amor do que boi cevado onde há ódio.", referencia: "Provérbios 15:17", tema: "contentamento" },
  { versiculo: "Melhor é o pouco do justo do que as riquezas de muitos ímpios.", referencia: "Salmos 37:16", tema: "contentamento" },
  { versiculo: "Não procureis as coisas grandes para vós mesmos.", referencia: "Jeremias 45:5", tema: "contentamento" },
  { versiculo: "Os olhos nunca se fartam de ver, nem os ouvidos de ouvir.", referencia: "Eclesiastes 1:8", tema: "contentamento" },
  { versiculo: "A vaidade das vaidades, tudo é vaidade.", referencia: "Eclesiastes 1:2", tema: "contentamento" },
  { versiculo: "Quem ama as riquezas não se satisfará com elas.", referencia: "Eclesiastes 5:10", tema: "contentamento" },
  { versiculo: "Não te afadiga para enriquecer; desiste da tua própria sabedoria.", referencia: "Provérbios 23:4", tema: "contentamento" },
  { versiculo: "Os desejos da carne e os desejos dos olhos e a ostentação dos bens são do mundo.", referencia: "1 João 2:16", tema: "contentamento" },
  { versiculo: "Não amardes o mundo, nem as coisas que estão no mundo.", referencia: "1 João 2:15", tema: "contentamento" },
  { versiculo: "Porque eu aprendi a contentar-me em qualquer estado que me encontre.", referencia: "Filipenses 4:11", tema: "contentamento" },
  { versiculo: "Melhor é a última palavra de uma coisa do que o seu começo.", referencia: "Eclesiastes 7:8", tema: "contentamento" },
  { versiculo: "O temor de Deus é melhor do que tanto ouro e prata.", referencia: "Sirácide 40:25", tema: "contentamento" },
  { versiculo: "Não acumules para ti tesouros sobre a terra, onde a traça e a ferrugem tudo consomem.", referencia: "Mateus 6:19", tema: "contentamento" },
  { versiculo: "Não há memória das coisas passadas, nem haverá das coisas que hão de vir.", referencia: "Eclesiastes 1:11", tema: "contentamento" },
  { versiculo: "Pois não recebereis nem mais nem menos do que conforme o vosso esforço.", referencia: "Gálatas 6:7", tema: "contentamento" },
  { versiculo: "Não coveis prata nem ouro.", referencia: "Atos 3:6", tema: "contentamento" },

  // PROTEÇÃO PATRIMONIAL (25)
  { versiculo: "O nome do Senhor é uma torre forte; o justo corre para ela e está seguro.", referencia: "Provérbios 18:10", tema: "protecao" },
  { versiculo: "O anjo do Senhor acampa em derredor dos que o temem e os livra.", referencia: "Salmos 34:7", tema: "protecao" },
  { versiculo: "Confiai nele em todo o tempo, ó povo; derramai diante dele o vosso coração.", referencia: "Salmos 62:8", tema: "protecao" },
  { versiculo: "O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre.", referencia: "Salmos 121:8", tema: "protecao" },
  { versiculo: "O que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", referencia: "Salmos 91:1", tema: "protecao" },
  { versiculo: "Porque ele ordenará a seus anjos que te guardem em todos os teus caminhos.", referencia: "Salmos 91:11", tema: "protecao" },
  { versiculo: "Não te esmoreças nem te desanimes, porque o Senhor teu Deus é contigo.", referencia: "Josué 1:9", tema: "protecao" },
  { versiculo: "O homem prudente vê o mal e esconde-se.", referencia: "Provérbios 22:3", tema: "protecao" },
  { versiculo: "Sê forte e corajoso! Não te apavores, nem te desanimes.", referencia: "Josué 1:9", tema: "protecao" },
  { versiculo: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador.", referencia: "Salmos 18:2", tema: "protecao" },
  { versiculo: "Guarda-me como a menina dos teus olhos; esconde-me à sombra das tuas asas.", referencia: "Salmos 17:8", tema: "protecao" },
  { versiculo: "O temor do Senhor leva à vida; dorme satisfeito e não é visitado pelo mal.", referencia: "Provérbios 19:23", tema: "protecao" },
  { versiculo: "O Senhor é a minha luz e a minha salvação; a quem temerei?", referencia: "Salmos 27:1", tema: "protecao" },
  { versiculo: "Porque o Senhor é a tua sombra protetora à tua mão direita.", referencia: "Salmos 121:5", tema: "protecao" },
  { versiculo: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus.", referencia: "Isaías 41:10", tema: "protecao" },
  { versiculo: "Quando te deitares não te aterrorizarás; sim, te deitarás, e o teu sono será suave.", referencia: "Provérbios 3:24", tema: "protecao" },
  { versiculo: "O Senhor é o teu guarda; o Senhor é a tua sombra à tua mão direita.", referencia: "Salmos 121:5", tema: "protecao" },
  { versiculo: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", referencia: "Salmos 46:1", tema: "protecao" },
  { versiculo: "O que encobre as suas transgressões não prosperará, mas o que as confessa e abandona alcançará misericórdia.", referencia: "Provérbios 28:13", tema: "protecao" },
  { versiculo: "Não temais os que matam o corpo, mas não podem matar a alma.", referencia: "Mateus 10:28", tema: "protecao" },
  { versiculo: "O ingênuo acredita em tudo, mas o prudente examina bem os seus passos.", referencia: "Provérbios 14:15", tema: "protecao" },
  { versiculo: "Ser cauteloso e previdente é sinal de sabedoria.", referencia: "Provérbios 14:15", tema: "protecao" },
  { versiculo: "O sábio tem olhos na cabeça.", referencia: "Eclesiastes 2:14", tema: "protecao" },
  { versiculo: "Nada fareis por contenda ou por vanglória, mas por humildade, cada um considerando os outros superiores a si mesmo.", referencia: "Filipenses 2:3", tema: "protecao" },
  { versiculo: "O Senhor preservará a tua saída e a tua entrada.", referencia: "Salmos 121:8", tema: "protecao" },
];

// ═══════════════════════════════════════
// FUNÇÕES DE ACESSO
// ═══════════════════════════════════════

export function getVersiculoAleatorio(): Versiculo {
  return versiculos[Math.floor(Math.random() * versiculos.length)];
}

export function getVersiculosPorTema(tema: Versiculo["tema"]): Versiculo[] {
  return versiculos.filter(v => v.tema === tema);
}

export function getVersiculoAleatorioDoTema(tema: Versiculo["tema"]): Versiculo {
  const lista = getVersiculosPorTema(tema);
  if (lista.length === 0) return getVersiculoAleatorio();
  return lista[Math.floor(Math.random() * lista.length)];
}

// Mapeamento contextual — qual tema usar em cada tela do app
export const temasPorContexto: Record<string, Versiculo["tema"]> = {
  dashboard: "prosperidade",
  assets: "protecao",
  nova_transacao: "poupanca",
  despesa: "contentamento",
  receita: "trabalho",
  dizimo: "dizimo",
  documentos: "sabedoria",
  metas: "heranca",
  goals: "heranca",
  projecao: "prosperidade",
  familia: "heranca",
  insights: "sabedoria",
  copilot: "sabedoria",
  challenges: "trabalho",
  relatorios: "poupanca",
  assinatura: "prosperidade",
};

export function getVersiculoContextual(contexto: keyof typeof temasPorContexto): Versiculo {
  const tema = temasPorContexto[contexto] || "sabedoria";
  return getVersiculoAleatorioDoTema(tema);
}
