project_id = "qclflqugqvsokthciish"

[functions.gemini-proxy]
verify_jwt = false

[functions.criar-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.portal-cliente]
verify_jwt = false

[functions.pdf-parser]
verify_jwt = false
