// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qclflqugqvsokthciish.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbGZscXVncXZzb2t0aGNpaXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NDk1MjUsImV4cCI6MjA4NjQyNTUyNX0.sNGuPEdDX0pkp3Gh9eKRiwR-06jwww_QV_6IMF2Jtvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});